export const schema = {
  receitas: [
    { key: "data", label: "Data", type: "date" },
    { key: "tipo", label: "Tipo", type: "select", options: ["Salário", "Renda Extra", "Comissão", "Reembolso", "Diversos"] },
    { key: "categoria", label: "Categoria" },
    { key: "descricao", label: "Descrição" },
    { key: "forma", label: "Forma de Recebimento" },
    { key: "valor", label: "Valor", type: "number" },
    { key: "obs", label: "Observações" },
  ],
  gastos: [
    { key: "data", label: "Data", type: "date" },
    { key: "grupo", label: "Grupo", type: "select", options: ["Fixo", "Variável", "Essencial", "Não Essencial"] },
    { key: "categoria", label: "Categoria" },
    { key: "subcategoria", label: "Subcategoria" },
    { key: "descricao", label: "Descrição" },
    { key: "forma", label: "Forma de Pagamento" },
    { key: "status", label: "Status", type: "select", options: ["Pago", "Pendente"] },
    { key: "valor", label: "Valor", type: "number" },
    { key: "obs", label: "Observações" },
  ],
  dividas: [
    { key: "credor", label: "Para quem devo" },
    { key: "valorTotal", label: "Valor total", type: "number" },
    { key: "parcelas", label: "Qtd parcelas", type: "number" },
    { key: "valorParcela", label: "Valor parcela", type: "number" },
    { key: "juros", label: "Juros (%)", type: "number" },
    { key: "vencimento", label: "Vencimento", type: "date" },
    { key: "status", label: "Status", type: "select", options: ["Em dia", "Atrasada", "Quitada"] },
    { key: "historico", label: "Histórico de pagamentos" },
    { key: "previsao", label: "Previsão quitação", type: "date" },
  ],
  receber: [
    { key: "pessoa", label: "Nome da pessoa" },
    { key: "motivo", label: "Motivo" },
    { key: "valorTotal", label: "Valor total", type: "number" },
    { key: "pago", label: "Quanto já foi pago", type: "number" },
    { key: "dataEmprestimo", label: "Data empréstimo", type: "date" },
    { key: "dataPrevista", label: "Data prevista pgto", type: "date" },
    { key: "status", label: "Status", type: "select", options: ["Aberto", "Parcial", "Recebido", "Atrasado"] },
    { key: "obs", label: "Observações" },
  ],
  parcelamentos: [
    { key: "descricao", label: "Compra" },
    { key: "cartao", label: "Cartão" },
    { key: "valorTotal", label: "Valor total", type: "number" },
    { key: "parcelas", label: "Número de parcelas", type: "number" },
    { key: "parcelaAtual", label: "Parcela atual", type: "number" },
    { key: "valorParcela", label: "Valor parcela", type: "number" },
    { key: "termino", label: "Previsão término", type: "date" },
  ],
  cartoes: [
    { key: "nome", label: "Nome do cartão" },
    { key: "limiteTotal", label: "Limite total", type: "number" },
    { key: "limiteDisponivel", label: "Limite disponível", type: "number" },
    { key: "faturaAtual", label: "Fatura atual", type: "number" },
    { key: "melhorDia", label: "Melhor dia compra" },
    { key: "vencimento", label: "Vencimento" },
    { key: "gastos", label: "Gastos por cartão", type: "number" },
  ],
  metas: [
    { key: "tipo", label: "Meta", type: "select", options: ["Reserva emergência", "Economia", "Compra", "Viagem", "Outra"] },
    { key: "valorAlvo", label: "Valor alvo", type: "number" },
    { key: "acumulado", label: "Valor acumulado", type: "number" },
    { key: "prazo", label: "Prazo", type: "date" },
    { key: "obs", label: "Observações" },
  ],
  planejamento: [
    { key: "area", label: "Área", type: "select", options: ["Imprevistos", "Planejamento mensal", "Assinaturas", "Gastos sazonais"] },
    { key: "descricao", label: "Descrição" },
    { key: "valorPrevisto", label: "Valor previsto", type: "number" },
    { key: "data", label: "Data", type: "date" },
    { key: "obs", label: "Observações" },
  ]
};
